{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  db-password: {{ .Values.secret.db_password | b64enc }}
  db-username: {{ .Values.secret.db_username | b64enc }}
{{- end }}